[package]
name = "typkg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
fs_extra = "1.3"
tempfile = "3.10"
colored = "2.1"
indicatif = "0.17"
